name: health_tracking_system
description: A healthcare app with patient and women's health dashboards.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  qr_flutter: ^4.0.0
  intl: ^0.20.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  http: ^1.2.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


